### ISSUE TITLE
Neslib.Utf8 - Compile error on Linux64: [Get|Reset|Set]MXCSR

### ISSUE THREAD

**Issue by dslutej** [neslib/Neslib.Json#3] opened 2020-02-28 14:53 UTC
Linux64:

[DCC Error] Neslib.Utf8.pas(1685): E2003 Undeclared identifier: 'GetMXCSR'
[DCC Error] Neslib.Utf8.pas(1687): E2003 Undeclared identifier: 'ResetMXCSR'
[DCC Error] Neslib.Utf8.pas(1783): E2003 Undeclared identifier: 'GetMXCSR'
[DCC Error] Neslib.Utf8.pas(1785): E2003 Undeclared identifier: 'SetMXCSR'

Windows64:

[dcc64 Warning] Neslib.Utf8.pas(1685): W1002 Symbol 'GetMXCSR' is specific to a platform
[dcc64 Warning] Neslib.Utf8.pas(1687): W1002 Symbol 'ResetMXCSR' is specific to a platform
[dcc64 Warning] Neslib.Utf8.pas(1783): W1002 Symbol 'GetMXCSR' is specific to a platform
[dcc64 Warning] Neslib.Utf8.pas(1785): W1002 Symbol 'SetMXCSR' is specific to a platform
[dcc64 Warning] Neslib.Utf8.pas(1853): W1002 Symbol 'SetMXCSR' is specific to a platform

**Comment by neslib** [comment] 2020-02-28 15:27
Thanks for the report. I don’t use Linux myself, so haven’t tested this. I will look into this when I’m back from a vacation.

**Comment by neslib** [comment] 2020-03-10 16:25
The issue should be fixed now. However, I don't use Linux so I haven't been able to test it.
Please let me know if this fixes the issue for you.

Note that the issue is in the Neslib submodule, so you need to pull this submodule as well.

**Comment by neslib** [comment] 2021-04-12 15:43
Haven't heard back in over a year, so I assume this issue is fixed now.

**Closed as completed by neslib** 2021-04-12 15:43 UTC
